[2023-12-10 17:39:52,666] ERROR log_exception() L825  Exception on /carro [DELETE] - call_trace=C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\app.py", line 117, in del_carro
    count = session.query(Carro).filter(Carro.placa == carro_placa).delete() # fazendo a remoção
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\orm\query.py", line 3181, in delete
    result: CursorResult[Any] = self.session.execute(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\engine\base.py", line 3268, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\engine\base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\sqlalchemy\pool\impl.py", line 158, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2023-12-10 17:39:52,676] INFO _log() L96   127.0.0.1 - - [10/Dec/2023 17:39:52] "[35m[1mDELETE /carro?placa=RJR1G51 HTTP/1.1[0m" 500 - - call_trace=C:\Users\phill\Desktop\mvp-full-stack\locadora_veiculos_api\env\Lib\site-packages\werkzeug\_internal.py L96  
